<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.nasdanika</groupId>
		<artifactId>parent</artifactId>
		<version>2026.9.0</version>
		<relativePath>../../poms/parent</relativePath>
	</parent>	
	<groupId>org.nasdanika.models.lifecycle</groupId>
	<artifactId>parent</artifactId>
	<!--<version>2026.9.0</version>-->
	<packaging>pom</packaging>
	<name>Nasdanika Lifecycle Model</name>
	<description>Lifecycle model, resource and resource factory</description>
	<url>https://lifecycle.models.nasdanika.org/</url>

	<scm>
		<url>https://github.com/Nasdanika-Models/lifecycle</url>
	</scm>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.nasdanika</groupId>
				<artifactId>bom</artifactId>
				<version>${project.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<modules>
		<module>model</module>
	</modules>

</project>
